export const colors = {
  primary: '#0f766e',
  primaryLight: '#f0fdfa',
  dark: '#1e293b',
  muted: '#94a3b8',
  border: '#e2e8f0',
  white: '#ffffff',
  bg: '#f8fafc',
  error: '#dc2626',
  errorBg: '#fef2f2',
  errorBorder: '#fecaca',
};

export const shared = {
  page: {
    minHeight: '100vh',
    background: colors.primaryLight,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '24px',
  },
  card: {
    background: colors.white,
    borderRadius: '16px',
    border: `1px solid ${colors.border}`,
    padding: '36px 32px',
    width: '100%',
    maxWidth: '420px',
  },
  logoRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    marginBottom: '24px',
  },
  logoDot: {
    width: '28px',
    height: '28px',
    background: colors.primary,
    borderRadius: '8px',
  },
  logoText: {
    fontSize: '18px',
    fontWeight: '800',
    color: colors.dark,
    letterSpacing: '-0.5px',
  },
  logoAccent: {
    color: colors.primary,
  },
  title: {
    fontSize: '22px',
    fontWeight: '700',
    color: colors.dark,
    marginBottom: '4px',
  },
  sub: {
    fontSize: '13px',
    color: colors.muted,
    marginBottom: '24px',
  },
  errorBox: {
    background: colors.errorBg,
    border: `1px solid ${colors.errorBorder}`,
    color: colors.error,
    borderRadius: '8px',
    padding: '10px 14px',
    fontSize: '13px',
    marginBottom: '16px',
  },
  field: {
    marginBottom: '16px',
  },
  label: {
    display: 'block',
    fontSize: '11px',
    fontWeight: '700',
    color: '#475569',
    letterSpacing: '0.06em',
    marginBottom: '6px',
  },
  input: {
    width: '100%',
    padding: '10px 14px',
    border: `1px solid ${colors.border}`,
    borderRadius: '8px',
    fontSize: '14px',
    color: colors.dark,
    background: colors.bg,
    outline: 'none',
  },
  btn: {
    width: '100%',
    padding: '12px',
    background: colors.primary,
    color: 'white',
    border: 'none',
    borderRadius: '8px',
    fontSize: '15px',
    fontWeight: '700',
    cursor: 'pointer',
    marginTop: '4px',
  },
  linkText: {
    textAlign: 'center',
    fontSize: '13px',
    color: colors.muted,
    marginTop: '20px',
  },
  link: {
    color: colors.primary,
    fontWeight: '600',
    textDecoration: 'none',
  },
};